"""Assemble candidate features on the GPU instead of once per candidate on the CPU.

Measured: `build_data_dict` ran 96 times per planning tick (32 samples x 3
autoregressive chunks) and cost ~1000 ms of the ~2300 ms tick -- more than the
world model itself. Almost all of it was `gather_features` rebuilding a
`cKDTree` for `dist2robot`, a 2789 x 500 nearest-neighbour query, eleven
timesteps deep, ninety-six times over.

Two observations make that avoidable:

  * Most channels do not depend on the candidate. Scene points, colours,
    normals, camera tensors and the centring are fixed by the OBSERVATION.
    Only four groups vary with the action -- robot flows, velocity,
    acceleration, and `dist2robot`.
  * The one expensive group is a distance matrix, which is what a GPU is for.
    `cdist` over (K*T, Ns, Nr) replaces the KD-trees outright.

So the invariant part is built once per `observe` through the REFERENCE path,
and only the four action-dependent groups are recomputed per candidate here.

**This module is a performance shortcut around PointWorld's own
`gather_features`, so it is only safe if it agrees with it exactly.**
`tests/test_fast_features.py` is that control: it builds the same candidates
both ways and requires the tensors to match. Do not edit this file without
re-running it -- a silent divergence here would look like a worse world model,
which is the most expensive kind of bug this project has.
"""

import numpy as np
import torch


def _channel_layout(args):
    """Start index and width of each named group, from the checkpoint's args.

    Read rather than hardcoded: the DROID checkpoint is single-arm (16 robot /
    31 scene channels) while DROID+BEHAVIOR is bimanual (17 / 42), and the
    difference is entirely in how many slots `gripper_open` occupies.
    """
    return list(args.robot_features), list(args.scene_features)


class FastFeatures:
    """Per-observation cache; call `batch()` per set of candidate actions."""

    def __init__(self, reference_dict, meta, args, device, n_gripper_slots):
        self.device = device
        self.args = args
        self.centre = torch.as_tensor(meta["centre"], dtype=torch.float32, device=device)
        self.T, self.Ns, self.Nr = meta["T"], meta["Ns"], meta["Nr"]
        self.n_grip = n_gripper_slots

        rf, sf = _channel_layout(args)
        self.robot_names, self.scene_names = rf, sf

        # Everything that the candidate cannot change, taken from the reference
        # assembly so it is bit-identical to the upstream pipeline.
        self.ref = reference_dict
        self.scene_feat0 = reference_dict["scene_features"][:, 0].clone()   # (1,Ns,Ds)
        self.robot_feat0 = reference_dict["robot_features"].clone()         # (1,T,Nr,Fr)
        self.scene_flows0 = reference_dict["scene_flows"].clone()           # (1,T,Ns,3)

        # Offsets of the action-dependent slices within the assembled vectors.
        self.r_off = self._offsets(rf, {"robot_flows": 3, "robot_colors": 3,
                                        "robot_normals": 3,
                                        "gripper_open": self.n_grip,
                                        "robot_velocity": 3,
                                        "robot_acceleration": 3})
        self.s_off = self._offsets(sf, {"scene_flows": 3, "scene_colors": 3,
                                        "scene_normals": 3,
                                        "gripper_open": self.n_grip * self.T,
                                        "dist2robot": self.T})

    @staticmethod
    def _offsets(names, widths):
        off, cur = {}, 0
        for n in names:
            off[n] = (cur, widths[n])
            cur += widths[n]
        return off

    @staticmethod
    def _derivatives(flows):
        """Mid-point velocity and acceleration, matching `compute_flow_derivatives`.

        Forward difference at the first step, central in the middle, backward at
        the last -- reproduced exactly rather than approximated, because these
        are 6 of the robot channels and a subtly different stencil would shift
        every one of them.
        """
        T = flows.shape[1]
        vel = torch.zeros_like(flows)
        acc = torch.zeros_like(flows)
        if T >= 2:
            vel[:, 0] = flows[:, 1] - flows[:, 0]
            if T >= 3:
                vel[:, 1:-1] = (flows[:, 2:] - flows[:, :-2]) / 2.0
                vel[:, -1] = flows[:, -1] - flows[:, -2]
        if T >= 3:
            acc[:, 0] = vel[:, 1] - vel[:, 0]
            if T >= 4:
                acc[:, 1:-1] = (vel[:, 2:] - vel[:, :-2]) / 2.0
                acc[:, -1] = vel[:, -1] - vel[:, -2]
        return vel, acc

    def batch(self, robot_flows, scene_flows=None):
        """(K,T,Nr,3) world-frame candidates -> a batched data_dict on the GPU.

        `scene_flows` (K,Ns,3) supplies the starting cloud for the second and
        third autoregressive chunks; omit it for the first.
        """
        rf = torch.as_tensor(np.ascontiguousarray(robot_flows), dtype=torch.float32,
                             device=self.device)
        if rf.dim() == 3:
            rf = rf[None]
        K = rf.shape[0]
        rf = rf - self.centre                                   # world -> centred

        scene = self.scene_flows0.expand(K, -1, -1, -1).clone()
        if scene_flows is not None:
            s = torch.as_tensor(np.ascontiguousarray(scene_flows), dtype=torch.float32,
                                device=self.device) - self.centre
            scene = s[:, None].expand(-1, self.T, -1, -1).contiguous()

        # ---- robot features: flows, velocity, acceleration ------------------
        robot_feat = self.robot_feat0.expand(K, -1, -1, -1).clone()
        vel, acc = self._derivatives(rf)
        for name, src in (("robot_flows", rf), ("robot_velocity", vel),
                          ("robot_acceleration", acc)):
            a, w = self.r_off[name]
            robot_feat[..., a:a + w] = src

        # ---- scene features: dist2robot only --------------------------------
        # Distance from each t=0 scene point to the nearest robot point at each
        # timestep. Shift-invariant, so the centring above does not affect it.
        scene_feat = self.scene_feat0.expand(K, -1, -1).clone()
        a, w = self.s_off["dist2robot"]
        # Chunked over time on purpose. The flat form materialises
        # (K*T, Ns, Nr) = 491 MB at K=8, and the allocation costs more than the
        # arithmetic saves -- measured 3.5x SLOWER than the CPU it replaced.
        # Per-timestep it is (K, Ns, Nr) = 45 MB, which stays resident.
        pts0 = scene[:, 0]                                       # (K,Ns,3)
        dist = torch.empty(K, self.T, pts0.shape[1], device=self.device)
        for t in range(self.T):
            dist[:, t] = torch.cdist(pts0, rf[:, t]).amin(dim=-1)
        scene_feat[..., a:a + w] = dist.permute(0, 2, 1)         # (K,Ns,T)

        # ---- scene coordinate channel, for chained chunks --------------------
        if scene_flows is not None:
            a, w = self.s_off["scene_flows"]
            scene_feat[..., a:a + w] = scene[:, 0]

        out = {
            "scene_flows": scene,
            "scene_features": scene_feat[:, None],               # (K,1,Ns,Ds)
            "scene_exists": self.ref["scene_exists"].expand(K, -1, -1),
            "robot_flows": rf,
            "robot_features": robot_feat,
            "robot_exists": self.ref["robot_exists"].expand(K, -1, -1),
            "__domain__": [self.ref["__domain__"][0]] * K,
        }
        for key, val in self.ref.items():
            if key.startswith("cam"):
                out[key] = val.expand(K, *val.shape[1:])
        return out
